// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.9
// source: collect_struct.proto

package stub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCollectListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int32  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Openid   string `protobuf:"bytes,2,opt,name=openid,proto3" json:"openid,omitempty"`
	Collects int32  `protobuf:"varint,3,opt,name=collects,proto3" json:"collects,omitempty"`
}

func (x *GetCollectListReq) Reset() {
	*x = GetCollectListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collect_struct_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCollectListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectListReq) ProtoMessage() {}

func (x *GetCollectListReq) ProtoReflect() protoreflect.Message {
	mi := &file_collect_struct_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectListReq.ProtoReflect.Descriptor instead.
func (*GetCollectListReq) Descriptor() ([]byte, []int) {
	return file_collect_struct_proto_rawDescGZIP(), []int{0}
}

func (x *GetCollectListReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetCollectListReq) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *GetCollectListReq) GetCollects() int32 {
	if x != nil {
		return x.Collects
	}
	return 0
}

type GetCollectListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32          `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string         `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	List []*CollectList `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetCollectListRsp) Reset() {
	*x = GetCollectListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collect_struct_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCollectListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectListRsp) ProtoMessage() {}

func (x *GetCollectListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_collect_struct_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectListRsp.ProtoReflect.Descriptor instead.
func (*GetCollectListRsp) Descriptor() ([]byte, []int) {
	return file_collect_struct_proto_rawDescGZIP(), []int{1}
}

func (x *GetCollectListRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetCollectListRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetCollectListRsp) GetList() []*CollectList {
	if x != nil {
		return x.List
	}
	return nil
}

type UpdateCollectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Collects int32 `protobuf:"varint,2,opt,name=collects,proto3" json:"collects,omitempty"`
}

func (x *UpdateCollectReq) Reset() {
	*x = UpdateCollectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collect_struct_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCollectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCollectReq) ProtoMessage() {}

func (x *UpdateCollectReq) ProtoReflect() protoreflect.Message {
	mi := &file_collect_struct_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCollectReq.ProtoReflect.Descriptor instead.
func (*UpdateCollectReq) Descriptor() ([]byte, []int) {
	return file_collect_struct_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCollectReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCollectReq) GetCollects() int32 {
	if x != nil {
		return x.Collects
	}
	return 0
}

type UpdateCollectRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *UpdateCollectRsp) Reset() {
	*x = UpdateCollectRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collect_struct_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCollectRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCollectRsp) ProtoMessage() {}

func (x *UpdateCollectRsp) ProtoReflect() protoreflect.Message {
	mi := &file_collect_struct_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCollectRsp.ProtoReflect.Descriptor instead.
func (*UpdateCollectRsp) Descriptor() ([]byte, []int) {
	return file_collect_struct_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCollectRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateCollectRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CollectList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Openid   string `protobuf:"bytes,2,opt,name=openid,proto3" json:"openid,omitempty"`
	Address  string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Collects int32  `protobuf:"varint,4,opt,name=collects,proto3" json:"collects,omitempty"`
}

func (x *CollectList) Reset() {
	*x = CollectList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collect_struct_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectList) ProtoMessage() {}

func (x *CollectList) ProtoReflect() protoreflect.Message {
	mi := &file_collect_struct_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectList.ProtoReflect.Descriptor instead.
func (*CollectList) Descriptor() ([]byte, []int) {
	return file_collect_struct_proto_rawDescGZIP(), []int{4}
}

func (x *CollectList) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CollectList) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *CollectList) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CollectList) GetCollects() int32 {
	if x != nil {
		return x.Collects
	}
	return 0
}

var File_collect_struct_proto protoreflect.FileDescriptor

var file_collect_struct_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x5f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x73, 0x74, 0x75, 0x62, 0x22, 0x60, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70,
	0x65, 0x6e, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x73, 0x22, 0x60,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x25, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x74, 0x75, 0x62, 0x2e, 0x43,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x22, 0x3e, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x73,
	0x22, 0x38, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x6b, 0x0a, 0x0b, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65,
	0x6e, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x73, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x73, 0x74, 0x75,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_collect_struct_proto_rawDescOnce sync.Once
	file_collect_struct_proto_rawDescData = file_collect_struct_proto_rawDesc
)

func file_collect_struct_proto_rawDescGZIP() []byte {
	file_collect_struct_proto_rawDescOnce.Do(func() {
		file_collect_struct_proto_rawDescData = protoimpl.X.CompressGZIP(file_collect_struct_proto_rawDescData)
	})
	return file_collect_struct_proto_rawDescData
}

var file_collect_struct_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_collect_struct_proto_goTypes = []interface{}{
	(*GetCollectListReq)(nil), // 0: stub.GetCollectListReq
	(*GetCollectListRsp)(nil), // 1: stub.GetCollectListRsp
	(*UpdateCollectReq)(nil),  // 2: stub.UpdateCollectReq
	(*UpdateCollectRsp)(nil),  // 3: stub.UpdateCollectRsp
	(*CollectList)(nil),       // 4: stub.CollectList
}
var file_collect_struct_proto_depIdxs = []int32{
	4, // 0: stub.GetCollectListRsp.list:type_name -> stub.CollectList
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_collect_struct_proto_init() }
func file_collect_struct_proto_init() {
	if File_collect_struct_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_collect_struct_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCollectListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collect_struct_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCollectListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collect_struct_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCollectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collect_struct_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCollectRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collect_struct_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_collect_struct_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_collect_struct_proto_goTypes,
		DependencyIndexes: file_collect_struct_proto_depIdxs,
		MessageInfos:      file_collect_struct_proto_msgTypes,
	}.Build()
	File_collect_struct_proto = out.File
	file_collect_struct_proto_rawDesc = nil
	file_collect_struct_proto_goTypes = nil
	file_collect_struct_proto_depIdxs = nil
}
